#+title: Guide pour la préparation du programme EIG

* Assurer aux EIG un accès aux données

/Ne sous-estimez pas le nombre d'obstacles qui peuvent se mettre en
travers de l'accès aux données./

Les données peuvent être accessible sous plusieurs formes :

- via une API publique ou privée ;
- via une procédure d'export d'une base de données ;
- via des fichiers accessibles à la demande.

Dans tous les cas, assurez-vous que les EIG ont accès au plus tôt aux
données elles-mêmes et à toute la documentation relative à ces données
(schémas de données, procédures d'utilisation des données, etc.)

* Préparer le poste de travail des EIG

/Consultez les EIG en amont sur leurs postes de travail./

Si les EIG souhaitent travailler depuis leurs ordinateurs personnels,
n'hésitez pas à les mettre en contact avec les services informatiques
pour que ceux-ci permettent les connexions depuis des ordinateurs qui
ne sont estampillés par l'administration.

Si les EIG travaillent depuis un poste fourni par l'administration,
prévoyez ces besoins :

- Pour un designer :: Demandez aux EIG s'ils ont besoin de *logiciels
     spécifiques* pour travailler : la suite Adobe est souvent demandée
     par les designer.

- Pour un data scientist :: Demandez aux EIG de *quelle puissance de
     calcul* ils ont besoin sur leur machine : en général, prévoir en
     16Go et 32Go pour des machines confortables.

- Pour un développeur web :: Demandez aux EIG de *quel système
     d'exploitation* ils ont besoin.  Les développeurs travaillent
     souvent avec des distributions de GNU/Linux (Ubuntu, Debian,
     ArchLinux, etc.)

- Pour tous les EIG :: Deux écrans de 17 à 19 pouces, et si l'espace
     de travail est un open space, un casque audio.

* Assurer aux EIG un accès ouvert à Internet

/Les EIG ont besoin d'un accès non bridé à Internet./

Si les données sur lesquelles les EIG travaillent ne sont accessibles
que sur un réseau interne à l'administration et inaccessible depuis
l'extérieur, prenez soin d'assurer par ailleurs un accès ouvert à
Internet depuis au moins une autre connexion.

* Communiquer sur le programme EIG avant son démarrage

Plusieurs mentors des deux éditions précédentes ont insisté sur
l'importance de bien communiquer sur le programme EIG avant même
l'arrivée des EIG dans les services.

Le site web EIG et les guides EIG pourront servir de ressources
à diffuser dans les administrations.

* Aider les EIG à identifier les bonnes personnes

/Aidez les EIG à faire connaissance en personne avec leurs futurs
alliés./

- AMD : L'administrateur ministériel des données
- DAJ : Le directeur des affaires juridiques
- DSI : Le directeur des Systèmes d'Information
- CIL : Le correspondant informatique et libertés
- S'il existe, le référent technique du service
  
* Aider les EIG à se familiariser avec le métier

/Aidez les EIG à mesurer tôt l'impact de leur projet et à trouver
rapidement leurs futurs utilisateurs./

Quelques idées :

- Proposer aux EIG un « stage d'immersion » sur le terrain, comme cela
  a été fait en 2018 pour le défi « Prévisecours ».

- Organiser la création d'une vidéo de présentation du projet pour
  créer de la convivialité dans l'équipe, comme cela a été fait en
  2018 pour le défi Archifiltre.

* Aider les EIG et mentors à se projeter dans le programme d'accompagnement

/Le programme d'accompagnement permet aux EIG et aux mentors de se
rencontrer régulièrement pour construire un collectif d'entre-aide./

- Prendre rapidement connaissance du calendrier des sessions
  d'accompagnement.

- Comprendre comment ce calendrier se construit au fil de l'eau.

* Trouver des soutiens dans les précédentes promotions EIG

Il est rare qu'une administration ou un défi ne présente aucun rapport
avec une administration ou un défi ayant précédemment participé au
programme EIG.  N'hésitez pas à contacter les EIG et mentors des
promotions précédentes pour vous guider dans le bon démarrage du défi.

* Partager des ressources administratives entre mentors

- Modèle de fiche de poste pour les ressources humaines.

- Modèle de notes de frais pour les EIG.

- Formulaire d'autorisation au télétravail.

- Contrat de confidentialité, correspondant au rappel des droits et
  devoirs des fonctionnaires.

* Aider les EIG à se positionner dans le défi

Les EIG ne sont ni prestataires ni en complète autonomie pour décider
de leur feuille de route.

La bonne marche du défi exige un *dialogue régulier* entre les mentors
et les EIG : les mentors doivent faire l'effort de bien comprendre la
feuille de route proposée par les EIG, et les EIG doivent communiquer
clairement sur ce qu'ils font.

Ce dialogue doit se mettre en place en suivant un calendrier stable,
indépendamment des sessions d'accompagnement.
