#+title: Glossaire

- Frontend / backend :: 

- Développeur :: 

- UX/UI designer :: 

- Défi :: 

- Mentor :: 

- API :: 

- Datascientiste :: 

- Logiciel libre :: logiciel publié sous une licence libre ou open
     source.

- Logiciel open source :: voir « logiciel libre ».

- Licence libre (ou « open source ») :: licence d'utilisation accordée
     par l'auteur d'un logiciel à ses utilisateurs, leur accordant au
     moins quatre libertés : celle d'utiliser le logiciel comme ils le
     veulent ; celle de l'étudier en lisant son code source ; celle de
     le modifier et de distribuer les modifications ; celle de
     redistribuer le logiciel, y compris commercialement.  Ces
     libertés peuvent être soumises à conditions, notamment
     l'application systématique de la même licence, ou d'une licence
     prodiguant les mêmes droits aux utilisateurs, aux copies de
     l'œuvre et aux œuvres dérivées.

- Licence « copyleft » :: Soit A un logiciel libre et B un logiciel
     libre qui en est dérivé.  Une licence est dite « copyleft » si
     elle impose que le logiciel B soit publié sous la même licence
     que le logiciel A.

- Licence « permissive » :: Soit A un logiciel libre et B un logiciel
     qui en est dérivé.  Une licence est dite « permissive » si elle
     n'impose pas de licence particulière sur les modifications
     apportées dans B au logiciel A.

- « Free software » :: Traduit par « logiciel libre ».  À noter que
     l'expression anglaise est ambiguë, « free » voulant dire à la
     fois « gratis » et « libre ».

- Opposition Libre / Open Source :: Le mouvement du « libre » est
     parcouru par deux tendances : l'une insiste sur l'importance
     éthique des logiciels libres, l'autre insiste sur leur qualité
     technique et leur potentiel économique.  La première tendance est
     portée par la Free Software Foundation (créée en 1985 par Richard
     M. Stallman et d'autres) et l'autre est portée par l'Open Source
     Initiative (créée en 1998 par Eric S. Raymond et d'autres).  La
     tendance libre privilégie des licences copyleft, l'autre des
     licences permissives.  Mais l'ensemble des logiciels/licences
     libres est identique à l'ensemble des logiciels/licences open
     source. 

