#+title: Infrastructure

Le programme EIG propose des ressources pour que les EIG, quel que
soit leur environnement de travail, accède aux outils dont ils ont
besoin.  Ils disposent notamment :

- d'un serveur pour déployer des containers et des machines virtuelles
- d'un serveur d'applications web déployables via Cloudron
- d'un serveur de déploiement d'application à la volée
- d'un serveur d'applications R Shiny
- d'un accès à des comptes AWS

* Serveur Proxmox VE

Voir la [[file:serveur.org][documentation détaillée]].

* Serveur d'applications web via Cloudron

[[https://cloudron.io][Cloudron]] est un logiciel libre permettant de transformer un serveur
GNU/Linux en service de déploiement d'applications web à la volée.

Etalab dispose d'un compte Cloudron sur une machine légère (2GO) et
propose aux EIG qui en aurait besoin de déployer des applications dans
[[https://cloudron.io/store/index.html][la liste des applications disponibles]] via Cloudron.

Si vous souhaitez déployer une application via Cloudron, envoyez un
mail aux EIG Link.

Le serveur cloudron est sauvegardé tous les jours par un envoi de
l'archive sur une instance AWS S3.

* Déploiement à la Heroku sur =www.eig-paas.org=

[[http://dokku.viewdocs.io/dokku/][Dokku]] est un logiciel libre permettant de transformer un serveur en
service de déploiement d'applications web à la [[https://www.heroku.com/][Heroku]].

Si vous souhaitez déployer une application sur un sous-domaine de ce
serveur (=mon-application.eig-paas.org=), envoyez un mail aux EIG Link.

Cette instance DigitalOcean de 1GO est sauvegardée par /snapshot/
hebdomadaire.

* Applications R sur =shiny.eig-forever.org=

=shiny.eig-apps.org= est un serveur d'applications développées en =R=.

Si vous souhaitez déployer une application R, envoyez un mail aux EIG
Link.

L'instance Vultr (2GO) est sauvegardée par /snapshot/ une fois par jour.

* Amazon Web Services (AWS)

Amazon Web Service (AWS) propose toute une gamme d'outils pour les
développeurs.  Le programme EIG dispose de crédits limités.  Si vous
avez besoin d'un service AWS, envoyez un mail aux EIG Link qui vous
créeront une instance =IAM=.

* Synthèse
  
| Fournisseur  | URL                     | RAM  | Service       | Description                  | Backup                            |
|--------------+-------------------------+------+---------------+------------------------------+-----------------------------------|
| OVH          | eig.etalab.gouv.fr:8006 | 32GO | Proxmox       | Déploiement containers / VM  | Copie manuelle 1j => eig-apps.org |
| DigitalOcean | eig-apps.org            | 2GO  | Cloudron      | Déploiement applications web | 1j => S3                          |
| Vultr        | shiny.eig-forever.org   | 1GO  | Shiny serveur | Déploiement applications R   | 1j (snapshot)                     |
| Vultr        | eig-paas.org            | 1GO  | Dokku         | Déploiement à la Heroku      | 1j (snapshot)                     |
