#+title: Mini-guide pour la réussite d'un défi EIG

Ce mini-guide veut attirer l'attention des mentors EIG sur des points
importants tout au long des 10 mois du défi EIG.

* La préparation du poste de travail

Les EIG sont designers, datascientistes, développeurs : leur
ordinateur n'est pas un point d'accès à l'administration, c'est leur
espace de travail.  Selon les outils qui leur sont familiers, ils
auront besoin d'un système d'exploitation et d'outils particuliers,
assurez-vous d'en parler tôt avec les EIG.  Ils auront aussi besoin de
se connecter à un Internet non bridé : si votre administration limite
les sites web accessibles et les ports ouverts vers l'extérieur,
vérifiez avec les EIG à ce que ces contraintes ne font pas obstacle à
leur productivité.

* La familiarisation avec le métier

Les EIG ne connaissent ni l'administration en général, ni les métiers
du service dans lequel il est accueilli, ni les usagers du défi qu'ils
relèvent.  Le premier mois est l'occasion de se familiariser avec
cela.  Vous pouvez proposer aux EIG une liste des acronymes utilisés
dans votre administration ; leur communiquer les documents
« métier » ; leur proposer une semaine d'immersion avec les usagers du
produit auquel il travaillera.

* L'immersion dans les données

Vous connaissez vos données par coeur mais les EIG les découvrent.
Pour faciliter leur prise en main, assurez-vous qu'ils ont accès à la
documentation nécessaire sur ces données et qu'ils peuvent facilement
les télécharger et les manipuler.  Si la collecte des données est un
enjeu de votre défi, proposez un calendrier précis sur les dates à
partir desquelles les données seront disponibles.

* La construction de l'équipe du défi

Au début du défi, vous faites connaissance avec les EIG comme ils font
connaissance avec vous, entre eux et avec les autres EIG de la
promotion.  Assurez-vous que les EIG ont la liste des personnes qui
pourront les aider au sein de votre administration.  Mettez en place
un rituel hebdomadaire de suivi du défi.  Créez un espace bienveillant
et ouvert, pour qu'ils puissent avancer sur le défi, exprimer les
difficultés qu'ils rencontrent et proposer de faire évoluer votre
feuille de route.

* La pérennisation des livrables

Les EIG ont pour mission de proposer rapidement des livrables.  Ils
auront à déployer du code rapidement, sans dépendre des contraintes de
votre DSI.  En revanche, le contact avec les DSI doit être établi le
plus tôt possible pour anticiper les questions de pérennisation.  Où
vivront les logiciels après 10 mois ?  Qui les maintiendra ?  Qui les
fera encore évoluer ?  Qui continuera de porter ces livrables, tant au
niveau technique que politique ?

* En résumé : les 6 facteurs de réussite

1. Un périmètre clair
2. Des équipes d’EIG pluridisciplinaires
3. Des mentors investis
4. Un environnement technique adapté
5. Un portage politique fort
6. Une liberté d’expérimenter

* Pour aller plus loin

- Le [[https://github.com/entrepreneur-interet-general/eig-link/blob/master/accueil-eig.org][guide d'accueil]] des EIG
- Les [[https://github.com/entrepreneur-interet-general/eig-link/blob/master/guides/guide-projet-eig.md][notes sur la gestion de projet]] EIG
- La [[https://entrepreneur-interet-general.etalab.gouv.fr/faq-eig.html][FAQ EIG]] et la [[https://entrepreneur-interet-general.etalab.gouv.fr/faq-administrations.html][FAQ administration]] sur le site EIG
- [[https://entrepreneur-interet-general.etalab.gouv.fr/blog/2018/05/23/6-facteurs-de-reussite-defi-eig.html][Les 6 facteurs de réussite d'un défi]] sur le blog EIG
